# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Joe-azure-pipeline

variables:
  runtime: 'win-x64'
  buildConfiguration: 'Release'
  framework: 'netcoreapp2.2'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'vs2017-win2016'
#    steps:
#    - script: dotnet build --configuration $(buildConfiguration)
#      displayName: 'dotnet build $(buildConfiguration)'

      steps:
      - task: PowerShell@2
        displayName: 'Supervisor DotNet Restore, Build, Publish PowerShell@2'
         inputs: 
         filepath: './Scripts/supervisor.build.ps1'
         #arguments: '-BuildDistrobution $(BuildDistrobution)'
         
- stage: Test
  jobs:
  - job: TestOnWindows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: echo Testing on Windows!

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: echo Deploying the code!
