# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  runtime: 'win-x64'
  buildConfiguration: 'Release'
  framework: 'netcoreapp2.2'

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  displayName: 'Supervisor Build'
  inputs:    
    filepath: './Scripts/supervisor.build.ps1'
    arguments: '-BuildDistrobution $(BuildDistrobution)'
